// Generates dist/tokens.css and dist/tokens.ts from tokens/*.json.
// Usage: node design-system/build.mjs [outDir]   (default: design-system/dist)
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

export const THEME_NAMES = ['personal', 'tooling', 'operations', 'data', 'public-service', 'playful'];
export const COLOR_KEYS = ['bg', 'surface', 'text', 'text-muted', 'rule', 'accent', 'on-accent', 'highlight', 'on-highlight'];
export const THEME_KEYS = ['mode', 'color', 'font-heading', 'text-body', 'radius', 'density'];
export const DENSITY = {
  compact: { pad: 6, gap: 12 },
  regular: { pad: 8, gap: 16 },
  comfortable: { pad: 12, gap: 24 },
};

export function loadTokens(dir = join(here, 'tokens')) {
  const foundation = JSON.parse(readFileSync(join(dir, 'foundation.json'), 'utf8'));
  const themes = {};
  for (const file of readdirSync(join(dir, 'themes')).filter((f) => f.endsWith('.json')).sort()) {
    themes[file.slice(0, -5)] = JSON.parse(readFileSync(join(dir, 'themes', file), 'utf8'));
  }
  return { foundation, themes };
}

const decl = (name, value) => `  --${name}: ${value};`;

function foundationBlock(f) {
  const lines = [decl('font-sans', f.font.sans), decl('font-mono', f.font.mono)];
  for (const [k, v] of Object.entries(f.text)) lines.push(decl(`text-${k}`, `${v}px`));
  lines.push(decl('measure', f.measure));
  for (const [k, v] of Object.entries(f.space)) lines.push(decl(`space-${k}`, `${v}px`));
  for (const [k, v] of Object.entries(f.status)) {
    lines.push(decl(`status-${k}`, v.bg), decl(`on-status-${k}`, v.fg));
  }
  lines.push(decl('focus', f.focus.outer), decl('focus-inner', f.focus.inner));
  return `:root {\n${lines.join('\n')}\n}`;
}

function colorLines(color, mode) {
  return [`  color-scheme: ${mode};`, ...COLOR_KEYS.map((k) => decl(`color-${k}`, color[k]))];
}

function themeBlock(name, t) {
  const d = DENSITY[t.density];
  const lines = [
    ...colorLines(t.color, t.mode),
    decl('font-heading', `var(--font-${t['font-heading']})`),
    decl('text-body', `${t['text-body']}px`),
    decl('radius', `${t.radius}px`),
    decl('density-pad', `${d.pad}px`),
    decl('density-gap', `${d.gap}px`),
  ];
  let css = `[data-theme="${name}"] {\n${lines.join('\n')}\n}`;
  if (t.dark) {
    const dark = colorLines(t.dark.color, 'dark').join('\n');
    css += `\n@media (prefers-color-scheme: dark) {\n  [data-theme="${name}"]:not([data-mode="light"]) {\n${dark.replace(/^/gm, '  ')}\n  }\n}`;
    css += `\n[data-theme="${name}"][data-mode="dark"] {\n${dark}\n}`;
  }
  return css;
}

export function renderCss({ foundation, themes }) {
  const header = '/* Generated by design-system/build.mjs. Do not edit. */';
  const blocks = Object.entries(themes).map(([n, t]) => themeBlock(n, t));
  return [header, foundationBlock(foundation), ...blocks].join('\n\n') + '\n';
}

export function renderTs({ foundation, themes }) {
  return [
    '// Generated by design-system/build.mjs. Do not edit.',
    `export const foundation = ${JSON.stringify(foundation, null, 2)} as const;`,
    `export const themes = ${JSON.stringify(themes, null, 2)} as const;`,
    'export type ThemeName = keyof typeof themes;',
    '',
  ].join('\n\n');
}

export function build(outDir = join(here, 'dist'), tokens = loadTokens()) {
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, 'tokens.css'), renderCss(tokens));
  writeFileSync(join(outDir, 'tokens.ts'), renderTs(tokens));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  build(process.argv[2]);
  console.log('built design-system/dist');
}
